CREATE DATABASE DBACME;

USE DBACME;

CREATE TABLE USERMODEL (
	USERID INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
	USERNAME NVARCHAR(MAX) NOT NULL,
	PASSWORDHASH VARBINARY(MAX) NOT NULL,
	PASSWORDSALT VARBINARY(MAX) NOT NULL
);

CREATE TABLE QUIZMODEL (
	QUIZID INT PRIMARY KEY IDENTITY NOT NULL,
	NAME NVARCHAR(MAX) NOT NULL,
	DESCRIPTION NVARCHAR(MAX) NOT NULL,
	UNIQUEID NVARCHAR(MAX) NOT NULL,
	USERREFID INT NOT NULL,
	CONSTRAINT FK_QUIZMODEL_USERMODEL_USERREFID FOREIGN KEY(USERREFID) REFERENCES USERMODEL(USERID) ON DELETE CASCADE
);


CREATE TABLE FIELDMODEL (
	FIELDID INT PRIMARY KEY IDENTITY NOT NULL,
	NAME NVARCHAR(MAX) NOT NULL,
	TITLE NVARCHAR(MAX) NOT NULL,
	REQUIRED NVARCHAR(1) NOT NULL,
	TYPEFIELD NVARCHAR(MAX) NOT NULL,
	QUIZREFID INT NOT NULL,
	CONSTRAINT FK_FIELDMODEL_QUIZMODEL_QUIZREFID FOREIGN KEY(QUIZREFID) REFERENCES QUIZMODEL(QUIZID) ON DELETE CASCADE
);

CREATE TABLE ANSWERMODEL (
	ANSWERID INT PRIMARY KEY IDENTITY NOT NULL,
	QUIZREFID INT NULL,
	FIELDREFID INT NULL,
	RESULT NVARCHAR(MAX) NOT NULL,
	CONSTRAINT FK_ANSWERMODEL_QUIZMODEL_QUIZREFID FOREIGN KEY(QUIZREFID) REFERENCES QUIZMODEL(QUIZID),
	CONSTRAINT FK_ANSWERMODEL_FIELDMODEL_FIELDREFID FOREIGN KEY(FIELDREFID) REFERENCES FIELDMODEL(FIELDID)
);

SELECT * FROM QUIZMODEL QM, FIELDMODEL FM
WHERE FM.QuizRefId = QM.QuizId;
